[versions]
"1.38.0" = { created_at = 2024-03-28T10:32:32.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.38.0" }
"1.39.0" = { created_at = 2024-05-15T09:37:19.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.39.0" }
"1.40.0" = { created_at = 2024-09-06T09:09:37.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.40.0" }
"1.41.0" = { created_at = 2024-10-26T18:51:15.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.41.0" }
"1.41.1" = { created_at = 2024-10-31T18:28:29.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.41.1" }
"1.42.0" = { created_at = 2025-01-05T00:21:57.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.42.0" }
"1.42.1" = { created_at = 2025-01-25T18:14:35.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.42.1" }
"1.42.2" = { created_at = 2025-03-02T00:39:17.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.42.2" }
"1.43.1" = { created_at = 2025-04-29T19:13:38.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.43.1" }
"1.43.2" = { created_at = 2025-09-04T18:34:56.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.43.2" }
"1.44.0" = { created_at = 2025-11-20T05:09:40.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.44.0" }
"1.44.1" = { created_at = 2025-11-20T21:19:48.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.44.1" }
"1.44.2" = { created_at = 2025-11-27T05:58:45.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.44.2" }
"1.44.3" = { created_at = 2025-11-27T21:36:21.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.44.3" }
"1.45.0" = { created_at = 2025-12-18T18:18:54.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.45.0" }
"1.45.1" = { created_at = 2025-12-29T03:00:01.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.45.1" }
"1.46.0" = { created_at = 2026-01-03T23:49:10.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.46.0" }
"1.46.1" = { created_at = 2026-01-15T18:09:30.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.46.1" }
"1.46.2" = { created_at = 2026-01-31T06:29:09.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.46.2" }
"1.46.3" = { created_at = 2026-02-02T14:10:01.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.46.3" }
"1.47.0" = { created_at = 2026-03-27T01:21:50.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.47.0" }
"1.47.1" = { created_at = 2026-03-29T05:28:17.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.47.1" }
"1.47.2" = { created_at = 2026-03-30T20:48:11.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.47.2" }
"1.48.0" = { created_at = 2026-06-11T14:12:09.000Z, release_url = "https://github.com/mitsuhiko/insta/releases/tag/1.48.0" }
