[versions]
"0.0.1" = { created_at = 2020-04-13T23:19:01.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.1" }
"0.0.1.1" = { created_at = 2020-05-31T20:48:54.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.1.1" }
"0.0.2" = { created_at = 2021-01-10T17:27:20.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.2" }
"0.0.3" = { created_at = 2021-02-02T08:23:01.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.3" }
"0.0.4" = { created_at = 2021-03-07T11:05:16.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.4" }
"0.0.5" = { created_at = 2021-04-03T09:37:49.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.5" }
"0.0.6" = { created_at = 2021-04-03T14:51:22.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.6" }
"0.0.7" = { created_at = 2021-07-11T19:32:01.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.7" }
"0.0.8" = { created_at = 2021-10-23T22:51:27.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.8" }
"0.0.12" = { created_at = 2022-01-19T11:35:00.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.12" }
"0.0.13" = { created_at = 2022-04-02T12:10:43.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.13" }
"0.0.14" = { created_at = 2022-05-22T17:57:19.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.14" }
"0.0.15" = { created_at = 2022-08-20T13:17:11.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.15" }
"0.0.16" = { created_at = 2022-10-12T09:20:27.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.16" }
"0.0.17" = { created_at = 2023-01-21T11:11:22.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.17" }
"0.0.18" = { created_at = 2023-04-02T19:01:05.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.18" }
"0.0.19" = { created_at = 2023-06-04T14:09:04.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.19" }
"0.0.20" = { created_at = 2023-07-14T12:07:20.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.20" }
"0.0.21" = { created_at = 2023-09-03T15:41:30.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.21" }
"0.0.22" = { created_at = 2023-10-15T13:50:01.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.22" }
"0.0.23" = { created_at = 2023-11-14T06:12:41.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.23" }
"0.0.26" = { created_at = 2024-04-26T21:41:31.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.26" }
"0.0.27" = { created_at = 2024-06-23T17:10:32.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.27" }
"0.0.28" = { created_at = 2024-11-16T19:24:18.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.28" }
"0.0.30" = { created_at = 2025-03-08T11:27:51.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.0.30" }
"0.1.0" = { created_at = 2025-05-24T21:03:22.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.1.0" }
"0.2.0" = { created_at = 2025-09-06T11:41:21.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.2.0" }
"0.2.2" = { created_at = 2025-09-09T19:43:58.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.2.2" }
"0.3.0" = { created_at = 2025-10-24T22:16:36.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.3.0" }
"0.4.0" = { created_at = 2025-11-09T22:39:03.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.4.0" }
"0.5.0" = { created_at = 2025-12-13T14:45:42.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.5.0" }
"latest-commit" = { created_at = 2026-01-17T10:33:24.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/latest-commit", prerelease = true }
"0.6.0" = { created_at = 2026-02-02T10:33:47.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.6.0" }
"0.7.0" = { created_at = 2026-03-08T21:01:33.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.7.0" }
"0.8.0" = { created_at = 2026-04-06T19:54:07.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.8.0" }
"0.9.0" = { created_at = 2026-05-30T09:10:38.000Z, release_url = "https://github.com/uutils/coreutils/releases/tag/0.9.0" }
