[versions]
"release-taplo-cli-0.6.7" = { created_at = 2022-06-16T19:26:42.000Z, release_url = "https://github.com/tamasfe/taplo/releases/tag/release-taplo-cli-0.6.7" }
"release-taplo-cli-0.6.8" = { created_at = 2022-06-18T11:40:19.000Z, release_url = "https://github.com/tamasfe/taplo/releases/tag/release-taplo-cli-0.6.8" }
"release-taplo-cli-0.7.0" = { created_at = 2022-09-01T20:34:51.000Z, release_url = "https://github.com/tamasfe/taplo/releases/tag/release-taplo-cli-0.7.0" }
"0.8.0" = { created_at = 2022-10-31T16:42:28.000Z, release_url = "https://github.com/tamasfe/taplo/releases/tag/0.8.0" }
"0.8.1" = { created_at = 2023-07-10T17:50:39.000Z, release_url = "https://github.com/tamasfe/taplo/releases/tag/0.8.1" }
"release-taplo-0.13.0" = { created_at = 2024-02-01T09:56:04.000Z, release_url = "https://github.com/tamasfe/taplo/releases/tag/release-taplo-0.13.0" }
"release-taplo-cli-0.9.0" = { created_at = 2024-02-01T02:22:12.000Z, release_url = "https://github.com/tamasfe/taplo/releases/tag/release-taplo-cli-0.9.0" }
"0.9.2" = { created_at = 2024-07-12T10:57:48.000Z, release_url = "https://github.com/tamasfe/taplo/releases/tag/0.9.2" }
"0.9.3" = { created_at = 2024-07-31T11:14:31.000Z, release_url = "https://github.com/tamasfe/taplo/releases/tag/0.9.3" }
"0.10.0" = { created_at = 2025-05-23T02:52:21.000Z, release_url = "https://github.com/tamasfe/taplo/releases/tag/0.10.0" }
