[versions]
"3.91" = { created_at = 2013-09-30T12:21:37.000Z, release_url = "https://github.com/upx/upx/releases/tag/v3.91" }
"3.92" = { created_at = 2016-12-11T15:54:12.000Z, release_url = "https://github.com/upx/upx/releases/tag/v3.92" }
"3.93" = { created_at = 2017-01-29T11:50:56.000Z, release_url = "https://github.com/upx/upx/releases/tag/v3.93" }
"3.94" = { created_at = 2017-05-12T13:00:13.000Z, release_url = "https://github.com/upx/upx/releases/tag/v3.94" }
"3.95" = { created_at = 2018-08-26T03:36:06.000Z, release_url = "https://github.com/upx/upx/releases/tag/v3.95" }
"3.96" = { created_at = 2020-01-22T21:53:16.000Z, release_url = "https://github.com/upx/upx/releases/tag/v3.96" }
"4.0.0" = { created_at = 2022-10-28T13:33:51.000Z, release_url = "https://github.com/upx/upx/releases/tag/v4.0.0" }
"4.0.1" = { created_at = 2022-11-16T22:50:35.000Z, release_url = "https://github.com/upx/upx/releases/tag/v4.0.1" }
"4.0.2" = { created_at = 2023-01-30T10:55:21.000Z, release_url = "https://github.com/upx/upx/releases/tag/v4.0.2" }
"4.1.0" = { created_at = 2023-08-08T09:25:13.000Z, release_url = "https://github.com/upx/upx/releases/tag/v4.1.0" }
"4.2.0" = { created_at = 2023-10-26T09:32:35.000Z, release_url = "https://github.com/upx/upx/releases/tag/v4.2.0" }
"4.2.1" = { created_at = 2023-11-01T11:35:24.000Z, release_url = "https://github.com/upx/upx/releases/tag/v4.2.1" }
"4.2.2" = { created_at = 2024-01-03T17:46:54.000Z, release_url = "https://github.com/upx/upx/releases/tag/v4.2.2" }
"4.2.3" = { created_at = 2024-03-27T18:44:25.000Z, release_url = "https://github.com/upx/upx/releases/tag/v4.2.3" }
"4.2.4" = { created_at = 2024-05-09T10:05:56.000Z, release_url = "https://github.com/upx/upx/releases/tag/v4.2.4" }
"5.0.0" = { created_at = 2025-02-20T16:53:01.000Z, release_url = "https://github.com/upx/upx/releases/tag/v5.0.0" }
"5.0.1" = { created_at = 2025-05-06T10:26:23.000Z, release_url = "https://github.com/upx/upx/releases/tag/v5.0.1" }
"5.0.2" = { created_at = 2025-07-20T12:43:41.000Z, release_url = "https://github.com/upx/upx/releases/tag/v5.0.2" }
"5.1.0" = { created_at = 2026-01-07T11:30:47.000Z, release_url = "https://github.com/upx/upx/releases/tag/v5.1.0" }
"5.1.1" = { created_at = 2026-03-05T15:00:49.000Z, release_url = "https://github.com/upx/upx/releases/tag/v5.1.1" }
"5.2.0" = { created_at = 2026-06-08T14:02:19.000Z, release_url = "https://github.com/upx/upx/releases/tag/v5.2.0" }
