name: python-precompiled
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

concurrency:
  group: python-precompiled
  cancel-in-progress: true

permissions:
  contents: write

env:
  GITHUB_API_TOKEN: ${{ secrets.MISE_GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.MISE_GITHUB_TOKEN }}
  DRY_RUN: 0
jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4
      - run: aube ci
      - run: ./scripts/python.sh
      - name: Upload .gz files to R2
        run: ./scripts/upload-gz.sh
        env:
          API_URL: https://mise-versions.jdx.dev
          API_SECRET: ${{ secrets.TOKEN_MANAGER_SECRET }}
